-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.4.0
-- Generated: 2018-11-20 15:32 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.io_redash_webhooks_event_1 (
    "schema_vendor"         VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_name"           VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_format"         VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_version"        VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "root_id"               CHAR(36)      ENCODE RAW  NOT NULL,
    "root_tstamp"           TIMESTAMP     ENCODE ZSTD NOT NULL,
    "ref_root"              VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "ref_tree"              VARCHAR(1500) ENCODE ZSTD NOT NULL,
    "ref_parent"            VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "action"                VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "created_at"            VARCHAR(4096) ENCODE ZSTD NOT NULL,
    "org_id"                INT           ENCODE ZSTD NOT NULL,
    "additional_properties" VARCHAR(4096) ENCODE ZSTD,
    "object_id"             VARCHAR(4096) ENCODE ZSTD,
    "object_type"           VARCHAR(255)  ENCODE ZSTD,
    "user_id"               INT           ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.io_redash_webhooks_event_1 IS 'iglu:io.redash.webhooks/event/jsonschema/1-0-0';
