-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.2.0
-- Generated: 2017-12-13 10:21

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_mailgun_message_bounced_1 (
    "schema_vendor"    VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"      VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"    VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version"   VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"          CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"      TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"         VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"         VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"       VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "attachment_count" INT           ENCODE LZO,
    "campaign_id"      VARCHAR(4096) ENCODE LZO,
    "campaign_name"    VARCHAR(4096) ENCODE LZO,
    "code"             VARCHAR(8)    ENCODE LZO,
    "domain"           VARCHAR(256)  ENCODE LZO,
    "error"            VARCHAR(4096) ENCODE LZO,
    "mailing_list"     VARCHAR(4096) ENCODE LZO,
    "message_headers"  VARCHAR(4096) ENCODE LZO,
    "message_id"       VARCHAR(1024) ENCODE LZO,
    "notification"     VARCHAR(4096) ENCODE LZO,
    "recipient"        VARCHAR(256)  ENCODE LZO,
    "signature"        VARCHAR(128)  ENCODE LZO,
    "tag"              VARCHAR(4096) ENCODE LZO,
    "timestamp"        TIMESTAMP     ENCODE LZO,
    "token"            CHAR(50)      ENCODE LZO,
    "x_mailgun_sid"    VARCHAR(4096) ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_mailgun_message_bounced_1 IS 'iglu:com.mailgun/message_bounced/jsonschema/1-0-0';
