-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.2.0
-- Generated: 2017-12-06 11:52

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_mailgun_message_opened_1 (
    "schema_vendor"  VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"    VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"  VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version" VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"        CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"    TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"       VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"       VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"     VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "campaign_id"    VARCHAR(4096) ENCODE LZO,
    "campaign_name"  VARCHAR(4096) ENCODE LZO,
    "city"           VARCHAR(64)   ENCODE LZO,
    "client_name"    VARCHAR(64)   ENCODE LZO,
    "client_os"      VARCHAR(64)   ENCODE LZO,
    "client_type"    VARCHAR(64)   ENCODE LZO,
    "country"        VARCHAR(2)    ENCODE LZO,
    "device_type"    VARCHAR(64)   ENCODE LZO,
    "domain"         VARCHAR(256)  ENCODE LZO,
    "ip"             VARCHAR(15)   ENCODE LZO,
    "mailing_list"   VARCHAR(4096) ENCODE LZO,
    "message_id"     VARCHAR(1024) ENCODE LZO,
    "recipient"      VARCHAR(256)  ENCODE LZO,
    "region"         VARCHAR(8)    ENCODE LZO,
    "signature"      VARCHAR(128)  ENCODE LZO,
    "tag"            VARCHAR(4096) ENCODE LZO,
    "timestamp"      TIMESTAMP     ENCODE LZO,
    "token"          CHAR(50)      ENCODE LZO,
    "user_agent"     VARCHAR(1024) ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_mailgun_message_opened_1 IS 'iglu:com.mailgun/message_opened/jsonschema/1-0-0';
