-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.1.0
-- Generated: 2016-09-02 17:18

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_snowplowanalytics_snowplow_ad_conversion_1 (
    "schema_vendor"  VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_name"    VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_format"  VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_version" VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "root_id"        CHAR(36)         ENCODE RAW       NOT NULL,
    "root_tstamp"    TIMESTAMP        ENCODE LZO       NOT NULL,
    "ref_root"       VARCHAR(255)     ENCODE RUNLENGTH NOT NULL,
    "ref_tree"       VARCHAR(1500)    ENCODE RUNLENGTH NOT NULL,
    "ref_parent"     VARCHAR(255)     ENCODE RUNLENGTH NOT NULL,
    "action"         VARCHAR(4096)    ENCODE LZO,
    "advertiser_id"  VARCHAR(4096)    ENCODE LZO,
    "campaign_id"    VARCHAR(4096)    ENCODE LZO,
    "category"       VARCHAR(4096)    ENCODE LZO,
    "conversion_id"  VARCHAR(4096)    ENCODE LZO,
    "cost"           DOUBLE PRECISION ENCODE RAW,
    "cost_model"     VARCHAR(3)       ENCODE LZO,
    "initial_value"  DOUBLE PRECISION ENCODE RAW,
    "property"       VARCHAR(4096)    ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_snowplowanalytics_snowplow_ad_conversion_1 IS 'iglu:com.snowplowanalytics.snowplow/ad_conversion/jsonschema/1-0-0';
