-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.1.0
-- Generated: 2016-09-02 17:18

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_snowplowanalytics_snowplow_desktop_context_1 (
    "schema_vendor"          VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_name"            VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_format"          VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_version"         VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "root_id"                CHAR(36)         ENCODE RAW       NOT NULL,
    "root_tstamp"            TIMESTAMP        ENCODE LZO       NOT NULL,
    "ref_root"               VARCHAR(255)     ENCODE RUNLENGTH NOT NULL,
    "ref_tree"               VARCHAR(1500)    ENCODE RUNLENGTH NOT NULL,
    "ref_parent"             VARCHAR(255)     ENCODE RUNLENGTH NOT NULL,
    "os_type"                VARCHAR(4096)    ENCODE LZO       NOT NULL,
    "os_version"             VARCHAR(4096)    ENCODE LZO       NOT NULL,
    "device_manufacturer"    VARCHAR(4096)    ENCODE LZO,
    "device_model"           VARCHAR(4096)    ENCODE LZO,
    "device_processor_count" DOUBLE PRECISION ENCODE RAW,
    "os_is64_bit"            BOOLEAN          ENCODE RUNLENGTH,
    "os_service_pack"        VARCHAR(4096)    ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_snowplowanalytics_snowplow_desktop_context_1 IS 'iglu:com.snowplowanalytics.snowplow/desktop_context/jsonschema/1-0-0';
