script: "./ci/lint.bash"
after_script: "./ci/dev_mirror_sync.bash"
before_deploy: pip install --user awscli
deploy:
- provider: script
  skip_cleanup: true
  script: "./ci/push.bash"
  on:
    tags: true
    condition: '"$(./ci/is_release_tag.bash $TRAVIS_TAG)" != "" && $? == 0'
env:
  global:
  - secure: qcvBVPk1h8FHt7/HMgBd1JAYLjJn2055vMQI3mx3pMAf8Y70nY2kDeEyIgd7bJDg4ZpaNiCs3SDNxENLZ+RO2dRS5i1Od0P0zYLA6E9BUzaF1WkJ/HCEIg9xCblvB1TdPFz2TNmUQh6Lcbd5qBqFuWgnHT+GLJppRtwUSS6QojU=
  - secure: iLvRKQE5WOOcc8Ivq6P80sCZACF6fJcMt8P8wW5eXHnT0ERZyve8G1wNyNmfChStm0xwvUJFFE9FfDSjhtTgja5HZUb4fcyFKQhni+qDkHx2kYsRYN7yTC1jyk9blMNpoBzyNxsCWf+uXWp+Hii/zncCOqpycMtmTi6KCYkD7hI=
  # IGLU_SERVER_APIKEY
  - secure: KX3qt+B+0cl9K6FGeJkbx/ck0dLvpDv0f1KK86pcb0FBFME5MiZy/qdPL/CHJiZVaxnGic6JqRWCOO58u7mmFK6yAsgMK8jJ5N4pUckivcqBnSC2Ka+6vJAV3I7hRAgMZQh+jcIcQn3Glp5vzIFlmIQC3Ub33f+FHuJ3NxGBI4Q=
