-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.4.3
-- Generated: 2018-03-29 13:29

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_amazon_aws_ec2_instance_identity_document_1 (
    schema_vendor        varchar(128)  not null           encoding rle,
    schema_name          varchar(128)  not null           encoding rle,
    schema_format        varchar(128)  not null           encoding rle,
    schema_version       varchar(128)  not null           encoding rle,
    root_id              char(36)      not null           encoding gzip_comp,
    root_tstamp          timestamp     not null           encoding deltaval,
    ref_root             varchar(255)  not null           encoding rle,
    ref_tree             varchar(1500) not null           encoding rle,
    ref_parent           varchar(255)  not null           encoding rle,
    account_id           varchar(128) null               encoding gzip_comp,
    architecture         varchar(128) null               encoding gzip_comp,
    availability_zone    varchar(128) null               encoding gzip_comp,
    billing_products     varchar(5000) null               encoding gzip_comp,
    devpay_product_codes varchar(5000) null               encoding gzip_comp,
    image_id             char(12)      null               encoding gzip_comp,
    instance_id          varchar(19)   null               encoding gzip_comp,
    instance_type        varchar(128) null               encoding gzip_comp,
    kernel_id            char(12)      null               encoding gzip_comp,
    pending_time         timestamp     null               encoding gzip_comp,
    private_ip           varchar(15)   null               encoding gzip_comp,
    ramdisk_id           char(12)      null               encoding gzip_comp,
    region               varchar(128) null               encoding gzip_comp,
    version              varchar(128) null               encoding gzip_comp,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
ORDER BY 
    schema_vendor,
    schema_name,
    schema_format,
    schema_version,
    ref_root,
    ref_tree,
    ref_parent,
    root_tstamp,
    root_id
SEGMENTED BY 
    hash(root_id) ALL NODES
;

COMMENT ON TABLE atomic.com_amazon_aws_ec2_instance_identity_document_1 IS 'iglu:com.amazon.aws.ec2/instance_identity_document/jsonschema/1-0-0';
