-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.4.0
-- Generated: 2018-06-18 10:12 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_snowplowanalytics_snowplow_enrichments_iab_spiders_and_robots_enrichment_1 (
    "schema_vendor"                              VARCHAR(128)  ENCODE ZSTD      NOT NULL,
    "schema_name"                                VARCHAR(128)  ENCODE ZSTD      NOT NULL,
    "schema_format"                              VARCHAR(128)  ENCODE ZSTD      NOT NULL,
    "schema_version"                             VARCHAR(128)  ENCODE ZSTD      NOT NULL,
    "root_id"                                    CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"                                TIMESTAMP     ENCODE ZSTD      NOT NULL,
    "ref_root"                                   VARCHAR(255)  ENCODE ZSTD      NOT NULL,
    "ref_tree"                                   VARCHAR(1500) ENCODE ZSTD      NOT NULL,
    "ref_parent"                                 VARCHAR(255)  ENCODE ZSTD      NOT NULL,
    "enabled"                                    BOOLEAN       ENCODE RUNLENGTH NOT NULL,
    "name"                                       VARCHAR(4096) ENCODE ZSTD      NOT NULL,
    "parameters.exclude_useragent_file.database" CHAR(19)      ENCODE ZSTD      NOT NULL,
    "parameters.exclude_useragent_file.uri"      VARCHAR(4096) ENCODE ZSTD      NOT NULL,
    "parameters.include_useragent_file.database" CHAR(19)      ENCODE ZSTD      NOT NULL,
    "parameters.include_useragent_file.uri"      VARCHAR(4096) ENCODE ZSTD      NOT NULL,
    "parameters.ip_file.database"                CHAR(27)      ENCODE ZSTD      NOT NULL,
    "parameters.ip_file.uri"                     VARCHAR(4096) ENCODE ZSTD      NOT NULL,
    "vendor"                                     VARCHAR(4096) ENCODE ZSTD      NOT NULL,
    "parameters.http_password"                   VARCHAR(4096) ENCODE ZSTD,
    "parameters.http_username"                   VARCHAR(4096) ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_snowplowanalytics_snowplow_enrichments_iab_spiders_and_robots_enrichment_1 IS 'iglu:com.snowplowanalytics.snowplow.enrichments/iab_spiders_and_robots_enrichment/jsonschema/1-0-0';
