-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.4.1
-- Generated: 2018-10-01 18:33 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_amazon_aws_ec2_instance_identity_document_1 (
    "schema_vendor"        VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_name"          VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_format"        VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_version"       VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "root_id"              CHAR(36)      ENCODE RAW  NOT NULL,
    "root_tstamp"          TIMESTAMP     ENCODE ZSTD NOT NULL,
    "ref_root"             VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "ref_tree"             VARCHAR(1500) ENCODE ZSTD NOT NULL,
    "ref_parent"           VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "account_id"           VARCHAR(4096) ENCODE ZSTD,
    "architecture"         VARCHAR(4096) ENCODE ZSTD,
    "availability_zone"    VARCHAR(4096) ENCODE ZSTD,
    "billing_products"     VARCHAR(5000) ENCODE ZSTD,
    "devpay_product_codes" VARCHAR(5000) ENCODE ZSTD,
    "image_id"             VARCHAR(21)   ENCODE ZSTD,
    "instance_id"          VARCHAR(21)   ENCODE ZSTD,
    "instance_type"        VARCHAR(4096) ENCODE ZSTD,
    "kernel_id"            VARCHAR(21)   ENCODE ZSTD,
    "pending_time"         TIMESTAMP     ENCODE ZSTD,
    "private_ip"           VARCHAR(15)   ENCODE ZSTD,
    "ramdisk_id"           VARCHAR(21)   ENCODE ZSTD,
    "region"               VARCHAR(4096) ENCODE ZSTD,
    "version"              VARCHAR(4096) ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_amazon_aws_ec2_instance_identity_document_1 IS 'iglu:com.amazon.aws.ec2/instance_identity_document/jsonschema/1-0-0';
