-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.6.0
-- Generated: 2020-02-12 18:56 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.dev_amp_snowplow_amp_page_ping_1 (
    "schema_vendor"      VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_name"        VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_format"      VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_version"     VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "root_id"            CHAR(36)      ENCODE RAW  NOT NULL,
    "root_tstamp"        TIMESTAMP     ENCODE ZSTD NOT NULL,
    "ref_root"           VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "ref_tree"           VARCHAR(1500) ENCODE ZSTD NOT NULL,
    "ref_parent"         VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "scroll_height"      BIGINT        ENCODE ZSTD,
    "scroll_left"        BIGINT        ENCODE ZSTD,
    "scroll_top"         BIGINT        ENCODE ZSTD,
    "scroll_width"       BIGINT        ENCODE ZSTD,
    "total_engaged_time" BIGINT        ENCODE ZSTD,
    "viewport_height"    BIGINT        ENCODE ZSTD,
    "viewport_width"     BIGINT        ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.dev_amp_snowplow_amp_page_ping_1 IS 'iglu:dev.amp.snowplow/amp_page_ping/jsonschema/1-0-0';
