-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.1.0
-- Generated: 2016-09-02 17:18

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.org_w3_performance_timing_1 (
    "schema_vendor"                  VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"                    VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"                  VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version"                 VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"                        CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"                    TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"                       VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"                       VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"                     VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "chrome_first_paint"             BIGINT        ENCODE LZO,
    "connect_end"                    BIGINT        ENCODE LZO,
    "connect_start"                  BIGINT        ENCODE LZO,
    "dom_complete"                   BIGINT        ENCODE LZO,
    "dom_content_loaded_event_end"   BIGINT        ENCODE LZO,
    "dom_content_loaded_event_start" BIGINT        ENCODE LZO,
    "dom_interactive"                BIGINT        ENCODE LZO,
    "dom_loading"                    BIGINT        ENCODE LZO,
    "domain_lookup_end"              BIGINT        ENCODE LZO,
    "domain_lookup_start"            BIGINT        ENCODE LZO,
    "fetch_start"                    BIGINT        ENCODE LZO,
    "load_event_end"                 BIGINT        ENCODE LZO,
    "load_event_start"               BIGINT        ENCODE LZO,
    "ms_first_paint"                 BIGINT        ENCODE LZO,
    "navigation_start"               BIGINT        ENCODE LZO,
    "proxy_end"                      BIGINT        ENCODE LZO,
    "proxy_start"                    BIGINT        ENCODE LZO,
    "redirect_end"                   BIGINT        ENCODE LZO,
    "redirect_start"                 BIGINT        ENCODE LZO,
    "request_end"                    BIGINT        ENCODE LZO,
    "request_start"                  BIGINT        ENCODE LZO,
    "response_end"                   BIGINT        ENCODE LZO,
    "response_start"                 BIGINT        ENCODE LZO,
    "secure_connection_start"        BIGINT        ENCODE LZO,
    "unload_event_end"               BIGINT        ENCODE LZO,
    "unload_event_start"             BIGINT        ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.org_w3_performance_timing_1 IS 'iglu:org.w3/PerformanceTiming/jsonschema/1-0-0';
