-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.4.1
-- Generated: 2018-10-11 05:02 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_callrail_call_complete_1 (
    "schema_vendor"         VARCHAR(128)     ENCODE ZSTD      NOT NULL,
    "schema_name"           VARCHAR(128)     ENCODE ZSTD      NOT NULL,
    "schema_format"         VARCHAR(128)     ENCODE ZSTD      NOT NULL,
    "schema_version"        VARCHAR(128)     ENCODE ZSTD      NOT NULL,
    "root_id"               CHAR(36)         ENCODE RAW       NOT NULL,
    "root_tstamp"           TIMESTAMP        ENCODE ZSTD      NOT NULL,
    "ref_root"              VARCHAR(255)     ENCODE ZSTD      NOT NULL,
    "ref_tree"              VARCHAR(1500)    ENCODE ZSTD      NOT NULL,
    "ref_parent"            VARCHAR(255)     ENCODE ZSTD      NOT NULL,
    "datetime"              TIMESTAMP        ENCODE ZSTD      NOT NULL,
    "id"                    VARCHAR(4096)    ENCODE ZSTD      NOT NULL,
    "answered"              BOOLEAN          ENCODE RUNLENGTH,
    "callercity"            VARCHAR(4096)    ENCODE ZSTD,
    "callercountry"         VARCHAR(4096)    ENCODE ZSTD,
    "callername"            VARCHAR(4096)    ENCODE ZSTD,
    "callernum"             VARCHAR(4096)    ENCODE ZSTD,
    "callerstate"           VARCHAR(4096)    ENCODE ZSTD,
    "callerzip"             VARCHAR(4096)    ENCODE ZSTD,
    "callsource"            VARCHAR(4096)    ENCODE ZSTD,
    "customer_city"         VARCHAR(4096)    ENCODE ZSTD,
    "customer_country"      VARCHAR(4096)    ENCODE ZSTD,
    "customer_name"         VARCHAR(4096)    ENCODE ZSTD,
    "customer_phone_number" VARCHAR(4096)    ENCODE ZSTD,
    "customer_state"        VARCHAR(4096)    ENCODE ZSTD,
    "customer_zip"          VARCHAR(4096)    ENCODE ZSTD,
    "destinationnum"        VARCHAR(4096)    ENCODE ZSTD,
    "device_type"           VARCHAR(4096)    ENCODE ZSTD,
    "duration"              DOUBLE PRECISION ENCODE RAW,
    "first_call"            BOOLEAN          ENCODE RUNLENGTH,
    "ga"                    VARCHAR(4096)    ENCODE ZSTD,
    "gclid"                 VARCHAR(4096)    ENCODE ZSTD,
    "ip"                    VARCHAR(4096)    ENCODE ZSTD,
    "keywords"              VARCHAR(4096)    ENCODE ZSTD,
    "kissmetrics_id"        VARCHAR(4096)    ENCODE ZSTD,
    "landingpage"           VARCHAR(4096)    ENCODE ZSTD,
    "recording"             VARCHAR(4096)    ENCODE ZSTD,
    "referrer"              VARCHAR(4096)    ENCODE ZSTD,
    "referrermedium"        VARCHAR(4096)    ENCODE ZSTD,
    "trackingnum"           VARCHAR(4096)    ENCODE ZSTD,
    "transcription"         VARCHAR(4096)    ENCODE ZSTD,
    "utm_campaign"          VARCHAR(4096)    ENCODE ZSTD,
    "utm_content"           VARCHAR(4096)    ENCODE ZSTD,
    "utm_medium"            VARCHAR(4096)    ENCODE ZSTD,
    "utm_source"            VARCHAR(4096)    ENCODE ZSTD,
    "utm_term"              VARCHAR(4096)    ENCODE ZSTD,
    "utma"                  VARCHAR(4096)    ENCODE ZSTD,
    "utmb"                  VARCHAR(4096)    ENCODE ZSTD,
    "utmc"                  VARCHAR(4096)    ENCODE ZSTD,
    "utmv"                  VARCHAR(4096)    ENCODE ZSTD,
    "utmx"                  VARCHAR(4096)    ENCODE ZSTD,
    "utmz"                  VARCHAR(4096)    ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_callrail_call_complete_1 IS 'iglu:com.callrail/call_complete/jsonschema/1-0-2';
