-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.1.0
-- Generated: 2016-09-02 17:18

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_callrail_call_complete_1 (
    "schema_vendor"         VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_name"           VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_format"         VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_version"        VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "root_id"               CHAR(36)         ENCODE RAW       NOT NULL,
    "root_tstamp"           TIMESTAMP        ENCODE LZO       NOT NULL,
    "ref_root"              VARCHAR(255)     ENCODE RUNLENGTH NOT NULL,
    "ref_tree"              VARCHAR(1500)    ENCODE RUNLENGTH NOT NULL,
    "ref_parent"            VARCHAR(255)     ENCODE RUNLENGTH NOT NULL,
    "datetime"              TIMESTAMP        ENCODE LZO       NOT NULL,
    "id"                    VARCHAR(4096)    ENCODE LZO       NOT NULL,
    "answered"              BOOLEAN          ENCODE RUNLENGTH,
    "callercity"            VARCHAR(4096)    ENCODE LZO,
    "callercountry"         VARCHAR(4096)    ENCODE LZO,
    "callername"            VARCHAR(4096)    ENCODE LZO,
    "callernum"             VARCHAR(4096)    ENCODE LZO,
    "callerstate"           VARCHAR(4096)    ENCODE LZO,
    "callerzip"             VARCHAR(4096)    ENCODE LZO,
    "callsource"            VARCHAR(4096)    ENCODE LZO,
    "destinationnum"        VARCHAR(4096)    ENCODE LZO,
    "duration"              DOUBLE PRECISION ENCODE RAW,
    "first_call"            BOOLEAN          ENCODE RUNLENGTH,
    "ga"                    VARCHAR(4096)    ENCODE LZO,
    "gclid"                 VARCHAR(4096)    ENCODE LZO,
    "ip"                    VARCHAR(4096)    ENCODE LZO,
    "keywords"              VARCHAR(4096)    ENCODE LZO,
    "kissmetrics_id"        VARCHAR(4096)    ENCODE LZO,
    "landingpage"           VARCHAR(4096)    ENCODE LZO,
    "recording"             VARCHAR(4096)    ENCODE LZO,
    "referrer"              VARCHAR(4096)    ENCODE LZO,
    "referrermedium"        VARCHAR(4096)    ENCODE LZO,
    "trackingnum"           VARCHAR(4096)    ENCODE LZO,
    "transcription"         VARCHAR(4096)    ENCODE LZO,
    "utm_campaign"          VARCHAR(4096)    ENCODE LZO,
    "utm_content"           VARCHAR(4096)    ENCODE LZO,
    "utm_medium"            VARCHAR(4096)    ENCODE LZO,
    "utm_source"            VARCHAR(4096)    ENCODE LZO,
    "utm_term"              VARCHAR(4096)    ENCODE LZO,
    "utma"                  VARCHAR(4096)    ENCODE LZO,
    "utmb"                  VARCHAR(4096)    ENCODE LZO,
    "utmc"                  VARCHAR(4096)    ENCODE LZO,
    "utmv"                  VARCHAR(4096)    ENCODE LZO,
    "utmx"                  VARCHAR(4096)    ENCODE LZO,
    "utmz"                  VARCHAR(4096)    ENCODE LZO,
    "device_type"           VARCHAR(4096)    ENCODE LZO,
    "customer_city"         VARCHAR(4096)    ENCODE LZO,
    "customer_country"      VARCHAR(4096)    ENCODE LZO,
    "customer_name"         VARCHAR(4096)    ENCODE LZO,
    "customer_phone_number" VARCHAR(4096)    ENCODE LZO,
    "customer_state"        VARCHAR(4096)    ENCODE LZO,
    "customer_zip"          VARCHAR(4096)    ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_callrail_call_complete_1 IS 'iglu:com.callrail/call_complete/jsonschema/1-0-2';
