-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.2.0
-- Generated: 2017-10-20 15:25

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_zendesk_snowplow_ticket_updated_1 (
    "schema_vendor"              VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"                VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"              VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version"             VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"                    CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"                TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"                   VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"                   VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"                 VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "account"                    VARCHAR(4096) ENCODE LZO       NOT NULL,
    "brand"                      VARCHAR(4096) ENCODE LZO       NOT NULL,
    "cc_names"                   VARCHAR(4096) ENCODE LZO       NOT NULL,
    "created_at"                 VARCHAR(4096) ENCODE LZO       NOT NULL,
    "in_business_hours"          BOOLEAN       ENCODE RUNLENGTH NOT NULL,
    "latest_comment"             VARCHAR(4096) ENCODE LZO       NOT NULL,
    "latest_comment_author_name" VARCHAR(4096) ENCODE LZO       NOT NULL,
    "latest_comment_is_public"   BOOLEAN       ENCODE RUNLENGTH NOT NULL,
    "status"                     VARCHAR(7)    ENCODE LZO       NOT NULL,
    "ticket_id"                  BIGINT        ENCODE LZO       NOT NULL,
    "ticket_title"               VARCHAR(4096) ENCODE LZO       NOT NULL,
    "updated_at"                 TIMESTAMP     ENCODE LZO       NOT NULL,
    "url"                        VARCHAR(4096) ENCODE LZO       NOT NULL,
    "via"                        VARCHAR(4096) ENCODE LZO       NOT NULL,
    "due_date"                   TIMESTAMP     ENCODE LZO,
    "external_id"                VARCHAR(4096) ENCODE LZO,
    "group_assigned"             VARCHAR(4096) ENCODE LZO,
    "organization_id"            BIGINT        ENCODE LZO,
    "organization_name"          VARCHAR(4096) ENCODE LZO,
    "priority"                   VARCHAR(6)    ENCODE LZO,
    "tags"                       VARCHAR(4096) ENCODE LZO,
    "ticket_type"                VARCHAR(8)    ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_zendesk_snowplow_ticket_updated_1 IS 'iglu:com.zendesk.snowplow/ticket_updated/jsonschema/1-0-0';
