-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.2.0
-- Generated: 2017-10-20 15:25

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_zendesk_snowplow_user_1 (
    "schema_vendor"  VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"    VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"  VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version" VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"        CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"    TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"       VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"       VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"     VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ticket_id"      BIGINT        ENCODE LZO       NOT NULL,
    "type"           VARCHAR(4096) ENCODE LZO       NOT NULL,
    "updated_at"     TIMESTAMP     ENCODE LZO       NOT NULL,
    "details"        VARCHAR(4096) ENCODE LZO,
    "email"          VARCHAR(4096) ENCODE LZO,
    "extended_role"  VARCHAR(4096) ENCODE LZO,
    "external_id"    VARCHAR(4096) ENCODE LZO,
    "first_name"     VARCHAR(4096) ENCODE LZO,
    "language"       VARCHAR(4096) ENCODE LZO,
    "last_name"      VARCHAR(4096) ENCODE LZO,
    "locale"         VARCHAR(4096) ENCODE LZO,
    "notes"          VARCHAR(4096) ENCODE LZO,
    "organization"   VARCHAR(4096) ENCODE LZO,
    "phone"          VARCHAR(4096) ENCODE LZO,
    "role"           VARCHAR(4096) ENCODE LZO,
    "signature"      VARCHAR(4096) ENCODE LZO,
    "tags"           VARCHAR(4096) ENCODE LZO,
    "time_zone"      VARCHAR(4096) ENCODE LZO,
    "user_id"        BIGINT        ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_zendesk_snowplow_user_1 IS 'iglu:com.zendesk.snowplow/user/jsonschema/1-0-0';
