-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.7.0
-- Generated: 2020-12-07 16:58 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_mailchimp_unsubscribe_1 (
    "schema_vendor"         VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_name"           VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_format"         VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_version"        VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "root_id"               CHAR(36)      ENCODE RAW  NOT NULL,
    "root_tstamp"           TIMESTAMP     ENCODE ZSTD NOT NULL,
    "ref_root"              VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "ref_tree"              VARCHAR(1500) ENCODE ZSTD NOT NULL,
    "ref_parent"            VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "data.action"           VARCHAR(4096) ENCODE ZSTD,
    "data.campaign_id"      VARCHAR(4096) ENCODE ZSTD,
    "data.email"            VARCHAR(4096) ENCODE ZSTD,
    "data.email_type"       VARCHAR(4096) ENCODE ZSTD,
    "data.id"               VARCHAR(4096) ENCODE ZSTD,
    "data.ip_opt"           VARCHAR(4096) ENCODE ZSTD,
    "data.list_id"          VARCHAR(4096) ENCODE ZSTD,
    "data.merges.email"     VARCHAR(4096) ENCODE ZSTD,
    "data.merges.fname"     VARCHAR(4096) ENCODE ZSTD,
    "data.merges.interests" VARCHAR(4096) ENCODE ZSTD,
    "data.merges.lname"     VARCHAR(4096) ENCODE ZSTD,
    "data.reason"           VARCHAR(4096) ENCODE ZSTD,
    "data.web_id"           VARCHAR(4096) ENCODE ZSTD,
    "fired_at"              TIMESTAMP     ENCODE ZSTD,
    "type"                  VARCHAR(4096) ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_mailchimp_unsubscribe_1 IS 'iglu:com.mailchimp/unsubscribe/jsonschema/1-0-0';
