-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.5.0
-- Generated: 2019-08-14 12:55 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_snowplowanalytics_monitor_application_1 (
    "schema_vendor"  VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_name"    VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_format"  VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_version" VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "root_id"        CHAR(36)      ENCODE RAW  NOT NULL,
    "root_tstamp"    TIMESTAMP     ENCODE ZSTD NOT NULL,
    "ref_root"       VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "ref_tree"       VARCHAR(1500) ENCODE ZSTD NOT NULL,
    "ref_parent"     VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "instance_id"    VARCHAR(36)   ENCODE ZSTD NOT NULL,
    "category"       VARCHAR(256)  ENCODE ZSTD,
    "cloud"          VARCHAR(7)    ENCODE ZSTD,
    "fabric"         VARCHAR(256)  ENCODE ZSTD,
    "inputs"         VARCHAR(5000) ENCODE ZSTD,
    "instance_name"  VARCHAR(256)  ENCODE ZSTD,
    "name"           VARCHAR(256)  ENCODE ZSTD,
    "outputs"        VARCHAR(5000) ENCODE ZSTD,
    "region"         VARCHAR(64)   ENCODE ZSTD,
    "tags"           VARCHAR(5000) ENCODE ZSTD,
    "version"        VARCHAR(32)   ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_snowplowanalytics_monitor_application_1 IS 'iglu:com.snowplowanalytics.monitor/application/jsonschema/1-0-0';
