-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.5.0
-- Generated: 2019-08-16 09:53 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_snowplowanalytics_monitor_database_1 (
    "schema_vendor"  VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_name"    VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_format"  VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_version" VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "root_id"        CHAR(36)      ENCODE RAW  NOT NULL,
    "root_tstamp"    TIMESTAMP     ENCODE ZSTD NOT NULL,
    "ref_root"       VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "ref_tree"       VARCHAR(1500) ENCODE ZSTD NOT NULL,
    "ref_parent"     VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "config_name"    VARCHAR(4096) ENCODE ZSTD NOT NULL,
    "cloud"          VARCHAR(7)    ENCODE ZSTD,
    "config_id"      VARCHAR(36)   ENCODE ZSTD,
    "dataset_id"     VARCHAR(1024) ENCODE ZSTD,
    "name"           VARCHAR(256)  ENCODE ZSTD,
    "project_id"     VARCHAR(30)   ENCODE ZSTD,
    "region"         VARCHAR(64)   ENCODE ZSTD,
    "schema"         VARCHAR(256)  ENCODE ZSTD,
    "tags"           VARCHAR(5000) ENCODE ZSTD,
    "type"           VARCHAR(256)  ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_snowplowanalytics_monitor_database_1 IS 'iglu:com.snowplowanalytics.monitor/database/jsonschema/1-0-0';
