-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.1.0
-- Generated: 2016-09-02 17:18

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_segment_context_1 (
    "schema_vendor"              VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_name"                VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_format"              VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_version"             VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "root_id"                    CHAR(36)         ENCODE RAW       NOT NULL,
    "root_tstamp"                TIMESTAMP        ENCODE LZO       NOT NULL,
    "ref_root"                   VARCHAR(255)     ENCODE RUNLENGTH NOT NULL,
    "ref_tree"                   VARCHAR(1500)    ENCODE RUNLENGTH NOT NULL,
    "ref_parent"                 VARCHAR(255)     ENCODE RUNLENGTH NOT NULL,
    "app.build"                  VARCHAR(1024)    ENCODE LZO,
    "app.name"                   VARCHAR(512)     ENCODE LZO,
    "app.version"                VARCHAR(1024)    ENCODE LZO,
    "campaign.content"           VARCHAR(8192)    ENCODE LZO,
    "campaign.medium"            VARCHAR(512)     ENCODE LZO,
    "campaign.name"              VARCHAR(1024)    ENCODE LZO,
    "campaign.source"            VARCHAR(512)     ENCODE LZO,
    "campaign.term"              VARCHAR(4096)    ENCODE LZO,
    "device.ad_tracking_enabled" BOOLEAN          ENCODE RUNLENGTH,
    "device.advertising_id"      CHAR(36)         ENCODE LZO,
    "device.id"                  CHAR(36)         ENCODE LZO,
    "device.manufacturer"        VARCHAR(512)     ENCODE LZO,
    "device.model"               VARCHAR(512)     ENCODE LZO,
    "device.name"                VARCHAR(1024)    ENCODE LZO,
    "device.token"               VARCHAR(128)     ENCODE LZO,
    "device.type"                VARCHAR(128)     ENCODE LZO,
    "ip"                         VARCHAR(15)      ENCODE LZO,
    "library.name"               VARCHAR(512)     ENCODE LZO,
    "library.version"            VARCHAR(512)     ENCODE LZO,
    "locale"                     VARCHAR(512)     ENCODE LZO,
    "location.city"              VARCHAR(512)     ENCODE LZO,
    "location.country"           VARCHAR(512)     ENCODE LZO,
    "location.latitude"          DOUBLE PRECISION ENCODE RAW,
    "location.longitude"         DOUBLE PRECISION ENCODE RAW,
    "location.speed"             BIGINT           ENCODE LZO,
    "network.bluetooth"          BOOLEAN          ENCODE RUNLENGTH,
    "network.carrier"            VARCHAR(1024)    ENCODE LZO,
    "network.cellular"           BOOLEAN          ENCODE RUNLENGTH,
    "network.wifi"               BOOLEAN          ENCODE RUNLENGTH,
    "os.name"                    VARCHAR(512)     ENCODE LZO,
    "os.version"                 VARCHAR(1024)    ENCODE LZO,
    "referrer.id"                VARCHAR(1024)    ENCODE LZO,
    "referrer.link"              VARCHAR(8192)    ENCODE LZO,
    "referrer.name"              VARCHAR(1024)    ENCODE LZO,
    "referrer.type"              VARCHAR(512)     ENCODE LZO,
    "referrer.url"               VARCHAR(8192)    ENCODE LZO,
    "screen.density"             INT              ENCODE LZO,
    "screen.height"              BIGINT           ENCODE LZO,
    "screen.width"               BIGINT           ENCODE LZO,
    "timezone"                   VARCHAR(128)     ENCODE LZO,
    "user_agent"                 VARCHAR(4096)    ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_segment_context_1 IS 'iglu:com.segment/context/jsonschema/1-0-0';
