-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.2.0
-- Generated: 2017-01-26 15:10

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.io_redash_webhooks_event_1 (
    "schema_vendor"         VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"           VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"         VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version"        VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"               CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"           TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"              VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"              VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"            VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "action"                VARCHAR(255)  ENCODE LZO       NOT NULL,
    "created_at"            TIMESTAMP     ENCODE LZO       NOT NULL,
    "id"                    INT           ENCODE LZO       NOT NULL,
    "org_id"                INT           ENCODE LZO       NOT NULL,
    "additional_properties" VARCHAR(4096) ENCODE LZO,
    "object_id"             VARCHAR(255)  ENCODE LZO,
    "object_type"           VARCHAR(255)  ENCODE LZO,
    "user_id"               INT           ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.io_redash_webhooks_event_1 IS 'iglu:io.redash.webhooks/event/jsonschema/1-0-0';
