CREATE TABLE IF NOT EXISTS atomic.com_snowplowanalytics_snowplow_elasticsearch_enriched_event_1 (
	-- Schema of this type
	schema_vendor		varchar(128)		not null		encoding rle,
	schema_name 		varchar(128)		not null		encoding rle,
	schema_format		varchar(128)		not null		encoding rle,
	schema_version		varchar(128)		not null		encoding rle,
	-- Parentage of this type
	root_id     		varchar(36) 		not null		encoding gzip_comp   ,
	root_tstamp 		timestamp   		not null		encoding deltaval    ,
	ref_root    		varchar(255)		not null		encoding rle         ,
	ref_tree    		varchar(1500)		not null		encoding rle         ,
	ref_parent  		varchar(255)		not null		encoding rle         ,
	-- Properties of this type
	app_id      		varchar(255)		null        		encoding gzip_comp   ,
	platform    		varchar(255)		null        		encoding gzip_comp   ,
	etl_tstamp  		varchar(255)		null        		encoding gzip_comp   ,
	collector_tstamp		varchar(255)		null        		encoding gzip_comp   ,
	dvce_tstamp 		varchar(255)		null        		encoding gzip_comp   ,
	event       		varchar(255)		null        		encoding gzip_comp   ,
	event_id    		varchar(255)		null        		encoding gzip_comp   ,
	txn_id      		integer     		null        		encoding auto        ,
	name_tracker		varchar(255)		null        		encoding gzip_comp   ,
	v_tracker   		varchar(255)		null        		encoding gzip_comp   ,
	v_collector 		varchar(255)		null        		encoding gzip_comp   ,
	v_etl       		varchar(255)		null        		encoding gzip_comp   ,
	user_id     		varchar(255)		null        		encoding gzip_comp   ,
	user_ipaddress		varchar(255)		null        		encoding gzip_comp   ,
	user_fingerprint		varchar(255)		null        		encoding gzip_comp   ,
	domain_userid		varchar(255)		null        		encoding gzip_comp   ,
	domain_sessionidx		integer     		null        		encoding auto        ,
	network_userid		varchar(255)		null        		encoding gzip_comp   ,
	geo_country 		varchar(255)		null        		encoding gzip_comp   ,
	geo_region  		varchar(255)		null        		encoding gzip_comp   ,
	geo_city    		varchar(255)		null        		encoding gzip_comp   ,
	geo_zipcode 		varchar(255)		null        		encoding gzip_comp   ,
	geo_latitude		number      		null        		encoding auto        ,
	geo_longitude		number      		null        		encoding auto        ,
	geo_region_name		varchar(255)		null        		encoding gzip_comp   ,
	geo_location		varchar(255)		null        		encoding gzip_comp   ,
	ip_isp      		varchar(255)		null        		encoding gzip_comp   ,
	ip_org      		varchar(255)		null        		encoding gzip_comp   ,
	ip_domain   		varchar(255)		null        		encoding gzip_comp   ,
	ip_netspeed 		varchar(255)		null        		encoding gzip_comp   ,
	page_url    		varchar(255)		null        		encoding gzip_comp   ,
	page_title  		varchar(255)		null        		encoding gzip_comp   ,
	page_referrer		varchar(255)		null        		encoding gzip_comp   ,
	page_urlscheme		varchar(255)		null        		encoding gzip_comp   ,
	page_urlhost		varchar(255)		null        		encoding gzip_comp   ,
	page_urlport		integer     		null        		encoding auto        ,
	page_urlpath		varchar(255)		null        		encoding gzip_comp   ,
	page_urlquery		varchar(255)		null        		encoding gzip_comp   ,
	page_urlfragment		varchar(255)		null        		encoding gzip_comp   ,
	refr_urlscheme		varchar(255)		null        		encoding gzip_comp   ,
	refr_urlhost		varchar(255)		null        		encoding gzip_comp   ,
	refr_urlport		integer     		null        		encoding auto        ,
	refr_urlpath		varchar(255)		null        		encoding gzip_comp   ,
	refr_urlquery		varchar(255)		null        		encoding gzip_comp   ,
	refr_urlfragment		varchar(255)		null        		encoding gzip_comp   ,
	refr_medium 		varchar(255)		null        		encoding gzip_comp   ,
	refr_source 		varchar(255)		null        		encoding gzip_comp   ,
	refr_term   		varchar(255)		null        		encoding gzip_comp   ,
	mkt_medium  		varchar(255)		null        		encoding gzip_comp   ,
	mkt_source  		varchar(255)		null        		encoding gzip_comp   ,
	mkt_term    		varchar(255)		null        		encoding gzip_comp   ,
	mkt_content 		varchar(255)		null        		encoding gzip_comp   ,
	mkt_campaign		varchar(255)		null        		encoding gzip_comp   ,
	se_category 		varchar(255)		null        		encoding gzip_comp   ,
	se_action   		varchar(255)		null        		encoding gzip_comp   ,
	se_label    		varchar(255)		null        		encoding gzip_comp   ,
	se_property 		varchar(255)		null        		encoding gzip_comp   ,
	se_value    		varchar(255)		null        		encoding gzip_comp   ,
	tr_orderid  		varchar(255)		null        		encoding gzip_comp   ,
	tr_affiliation		varchar(255)		null        		encoding gzip_comp   ,
	tr_total    		number      		null        		encoding auto        ,
	tr_tax      		number      		null        		encoding auto        ,
	tr_shipping 		number      		null        		encoding auto        ,
	tr_city     		varchar(255)		null        		encoding gzip_comp   ,
	tr_state    		varchar(255)		null        		encoding gzip_comp   ,
	tr_country  		varchar(255)		null        		encoding gzip_comp   ,
	ti_orderid  		varchar(255)		null        		encoding gzip_comp   ,
	ti_sku      		varchar(255)		null        		encoding gzip_comp   ,
	ti_name     		varchar(255)		null        		encoding gzip_comp   ,
	ti_category 		varchar(255)		null        		encoding gzip_comp   ,
	ti_price    		number      		null        		encoding auto        ,
	ti_quantity 		integer     		null        		encoding auto        ,
	pp_xoffset_min		integer     		null        		encoding auto        ,
	pp_xoffset_max		integer     		null        		encoding auto        ,
	pp_yoffset_min		integer     		null        		encoding auto        ,
	pp_yoffset_max		integer     		null        		encoding auto        ,
	useragent   		varchar(255)		null        		encoding gzip_comp   ,
	br_name     		varchar(255)		null        		encoding gzip_comp   ,
	br_family   		varchar(255)		null        		encoding gzip_comp   ,
	br_version  		varchar(255)		null        		encoding gzip_comp   ,
	br_type     		varchar(255)		null        		encoding gzip_comp   ,
	br_renderengine		varchar(255)		null        		encoding gzip_comp   ,
	br_lang     		varchar(255)		null        		encoding gzip_comp   ,
	br_features_pdf		boolean     		null        		encoding auto        ,
	br_features_flash		boolean     		null        		encoding auto        ,
	br_features_java		boolean     		null        		encoding auto        ,
	br_features_director		boolean     		null        		encoding auto        ,
	br_features_quicktime		boolean     		null        		encoding auto        ,
	br_features_realplayer		boolean     		null        		encoding auto        ,
	br_features_windowsmedia		boolean     		null        		encoding auto        ,
	br_features_gears		boolean     		null        		encoding auto        ,
	br_features_silverlight		boolean     		null        		encoding auto        ,
	br_cookies  		boolean     		null        		encoding auto        ,
	br_colordepth		varchar(255)		null        		encoding gzip_comp   ,
	br_viewwidth		integer     		null        		encoding auto        ,
	br_viewheight		integer     		null        		encoding auto        ,
	os_name     		varchar(255)		null        		encoding gzip_comp   ,
	os_family   		varchar(255)		null        		encoding gzip_comp   ,
	os_manufacturer		varchar(255)		null        		encoding gzip_comp   ,
	os_timezone 		varchar(255)		null        		encoding gzip_comp   ,
	dvce_type   		varchar(255)		null        		encoding gzip_comp   ,
	dvce_ismobile		boolean     		null        		encoding auto        ,
	dvce_screenwidth		integer     		null        		encoding auto        ,
	dvce_screenheight		integer     		null        		encoding auto        ,
	doc_charset 		varchar(255)		null        		encoding gzip_comp   ,
	doc_width   		integer     		null        		encoding auto        ,
	doc_height  		integer     		null        		encoding auto        
)
ORDER BY
	schema_vendor,
	schema_name,
	schema_format,
	schema_version,
	ref_root,
	ref_tree,
	ref_parent,
	root_tstamp,
	root_id
SEGMENTED BY
	hash(root_id) ALL NODES
;