-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.5.0
-- Generated: 2019-07-01 09:55 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_snowplowanalytics_monitor_application_status_1 (
    "schema_vendor"        VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_name"          VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_format"        VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "schema_version"       VARCHAR(128)  ENCODE ZSTD NOT NULL,
    "root_id"              CHAR(36)      ENCODE RAW  NOT NULL,
    "root_tstamp"          TIMESTAMP     ENCODE ZSTD NOT NULL,
    "ref_root"             VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "ref_tree"             VARCHAR(1500) ENCODE ZSTD NOT NULL,
    "ref_parent"           VARCHAR(255)  ENCODE ZSTD NOT NULL,
    "period_length_in_sec" BIGINT        ENCODE ZSTD NOT NULL,
    "avg_cpu_usage"        SMALLINT      ENCODE ZSTD,
    "avg_memory_usage"     BIGINT        ENCODE ZSTD,
    "avg_network_in"       BIGINT        ENCODE ZSTD,
    "avg_network_out"      BIGINT        ENCODE ZSTD,
    "in_app_stats"         VARCHAR(5000) ENCODE ZSTD,
    "node_specs"           VARCHAR(5000) ENCODE ZSTD,
    "node_type"            VARCHAR(4096) ENCODE ZSTD,
    "num_nodes"            BIGINT        ENCODE ZSTD,
    "period_end"           TIMESTAMP     ENCODE ZSTD,
    "period_start"         TIMESTAMP     ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_snowplowanalytics_monitor_application_status_1 IS 'iglu:com.snowplowanalytics.monitor/application_status/jsonschema/1-0-0';
