-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.3.0
-- Generated: 2018-01-10 13:34

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_google_cloud_gce_instance_metadata_1 (
    "schema_vendor"  VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"    VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"  VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version" VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"        CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"    TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"       VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"       VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"     VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "attributes"     VARCHAR(4096) ENCODE LZO       NOT NULL,
    "cpu_platform"   VARCHAR(64)   ENCODE LZO       NOT NULL,
    "hostname"       VARCHAR(255)  ENCODE LZO       NOT NULL,
    "id"             VARCHAR(32)   ENCODE LZO       NOT NULL,
    "image"          VARCHAR(128)  ENCODE LZO       NOT NULL,
    "machine_type"   VARCHAR(64)   ENCODE LZO       NOT NULL,
    "name"           VARCHAR(64)   ENCODE LZO       NOT NULL,
    "tags"           VARCHAR(5000) ENCODE LZO       NOT NULL,
    "zone"           VARCHAR(64)   ENCODE LZO       NOT NULL,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_google_cloud_gce_instance_metadata_1 IS 'iglu:com.google.cloud.gce/instance_metadata/jsonschema/1-0-0';
