-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.4.3
-- Generated: 2018-05-03 16:28

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_github_marketplace_purchase_1 (
    schema_vendor                                           varchar(128)  not null           encoding rle,
    schema_name                                             varchar(128)  not null           encoding rle,
    schema_format                                           varchar(128)  not null           encoding rle,
    schema_version                                          varchar(128)  not null           encoding rle,
    root_id                                                 char(36)      not null           encoding gzip_comp,
    root_tstamp                                             timestamp     not null           encoding deltaval,
    ref_root                                                varchar(255)  not null           encoding rle,
    ref_tree                                                varchar(1500) not null           encoding rle,
    ref_parent                                              varchar(255)  not null           encoding rle,
    action                                                  varchar(4096) null               encoding gzip_comp,
    effective_date                                          timestamp     null               encoding gzip_comp,
    marketplace_purchase_account_id                         int           null               encoding gzip_comp,
    marketplace_purchase_account_login                      varchar(4096) null               encoding gzip_comp,
    marketplace_purchase_account_organization_billing_email varchar(4096) null               encoding gzip_comp,
    marketplace_purchase_account_type                       varchar(4096) null               encoding gzip_comp,
    marketplace_purchase_billing_cycle                      varchar(4096) null               encoding gzip_comp,
    marketplace_purchase_free_trial_ends_on                 varchar(4096) null               encoding gzip_comp,
    marketplace_purchase_next_billing_date                  timestamp     null               encoding gzip_comp,
    marketplace_purchase_on_free_trial                      boolean       null               encoding auto,
    marketplace_purchase_plan_bullets                       varchar(5000) null               encoding gzip_comp,
    marketplace_purchase_plan_description                   varchar(4096) null               encoding gzip_comp,
    marketplace_purchase_plan_has_free_trial                boolean       null               encoding auto,
    marketplace_purchase_plan_id                            smallint      null               encoding gzip_comp,
    marketplace_purchase_plan_monthly_price_in_cents        smallint      null               encoding gzip_comp,
    marketplace_purchase_plan_name                          varchar(4096) null               encoding gzip_comp,
    marketplace_purchase_plan_price_model                   varchar(4096) null               encoding gzip_comp,
    marketplace_purchase_plan_unit_name                     varchar(4096) null               encoding gzip_comp,
    marketplace_purchase_plan_yearly_price_in_cents         smallint      null               encoding gzip_comp,
    marketplace_purchase_unit_count                         smallint      null               encoding gzip_comp,
    sender_avatar_url                                       varchar(4096) null               encoding gzip_comp,
    sender_email                                            varchar(4096) null               encoding gzip_comp,
    sender_events_url                                       varchar(4096) null               encoding gzip_comp,
    sender_followers_url                                    varchar(4096) null               encoding gzip_comp,
    sender_following_url                                    varchar(4096) null               encoding gzip_comp,
    sender_gists_url                                        varchar(4096) null               encoding gzip_comp,
    sender_gravatar_id                                      varchar(4096) null               encoding gzip_comp,
    sender_html_url                                         varchar(4096) null               encoding gzip_comp,
    sender_id                                               int           null               encoding gzip_comp,
    sender_login                                            varchar(4096) null               encoding gzip_comp,
    sender_organizations_url                                varchar(4096) null               encoding gzip_comp,
    sender_received_events_url                              varchar(4096) null               encoding gzip_comp,
    sender_repos_url                                        varchar(4096) null               encoding gzip_comp,
    sender_site_admin                                       boolean       null               encoding auto,
    sender_starred_url                                      varchar(4096) null               encoding gzip_comp,
    sender_subscriptions_url                                varchar(4096) null               encoding gzip_comp,
    sender_type                                             varchar(4096) null               encoding gzip_comp,
    sender_url                                              varchar(4096) null               encoding gzip_comp,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
ORDER BY 
    schema_vendor,
    schema_name,
    schema_format,
    schema_version,
    ref_root,
    ref_tree,
    ref_parent,
    root_tstamp,
    root_id
SEGMENTED BY 
    hash(root_id) ALL NODES
;

COMMENT ON TABLE atomic.com_github_marketplace_purchase_1 IS 'iglu:com.github/marketplace_purchase/jsonschema/1-0-0';
