-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.4.3
-- Generated: 2017-10-19 13:16
 
CREATE SCHEMA IF NOT EXISTS atomic;
 
CREATE TABLE IF NOT EXISTS atomic.com_chewy_user_info_1 (
    schema_vendor       varchar(128)  not null           encoding rle,
    schema_name         varchar(128)  not null           encoding rle,
    schema_format       varchar(128)  not null           encoding rle,
    schema_version      varchar(128)  not null           encoding rle,
    root_id             char(36)      not null           encoding gzip_comp,
    root_tstamp         timestamp     not null           encoding deltaval,
    ref_root            varchar(255)  not null           encoding rle,
    ref_tree            varchar(1500) not null           encoding rle,
    ref_parent          varchar(255)  not null           encoding rle,
    address             varchar(4096) null               encoding gzip_comp,
    average_order_value varchar(4096) null               encoding gzip_comp,
    city                varchar(4096) null               encoding gzip_comp,
    country             varchar(4096) null               encoding gzip_comp,
    customer_id         varchar(4096) null               encoding gzip_comp,
    email               varchar(4096) null               encoding gzip_comp,
    first_order_date    varchar(4096) null               encoding gzip_comp,
    first_name          varchar(4096) null               encoding gzip_comp,
    has_ordered         boolean       null               encoding auto,
    last_order_date     varchar(4096) null               encoding gzip_comp,
    last_order_pet      varchar(4096) null               encoding gzip_comp,
    last_name           varchar(4096) null               encoding gzip_comp,
    mobile              varchar(4096) null               encoding gzip_comp,
    registration_date   varchar(4096) null               encoding gzip_comp,
    repeat_customer     boolean       null               encoding auto,
    state               varchar(4096) null               encoding gzip_comp,
    zip                 varchar(4096) null               encoding gzip_comp,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
ORDER BY
    schema_vendor,
    schema_name,
    schema_format,
    schema_version,
    ref_root,
    ref_tree,
    ref_parent,
    root_tstamp,
    root_id
SEGMENTED BY
    hash(root_id) ALL NODES
;
 
COMMENT ON TABLE atomic.com_chewy_user_info_1 IS 'iglu:com.chewy/user_info/jsonschema/1-0-0';