-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.2.0
-- Generated: 2017-09-19 16:16

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_mparticle_snowplow_product_event_1 (
    "schema_vendor"       VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_name"         VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_format"       VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "schema_version"      VARCHAR(128)     ENCODE RUNLENGTH NOT NULL,
    "root_id"             CHAR(36)         ENCODE RAW       NOT NULL,
    "root_tstamp"         TIMESTAMP        ENCODE LZO       NOT NULL,
    "ref_root"            VARCHAR(255)     ENCODE RUNLENGTH NOT NULL,
    "ref_tree"            VARCHAR(1500)    ENCODE RUNLENGTH NOT NULL,
    "ref_parent"          VARCHAR(255)     ENCODE RUNLENGTH NOT NULL,
    "action"              VARCHAR(4096)    ENCODE LZO       NOT NULL,
    "checkout_options"    VARCHAR(4096)    ENCODE LZO,
    "checkout_step"       BIGINT           ENCODE LZO,
    "coupon_code"         VARCHAR(4096)    ENCODE LZO,
    "currency"            VARCHAR(4096)    ENCODE LZO,
    "product_action_list" VARCHAR(4096)    ENCODE LZO,
    "products"            VARCHAR(5000)    ENCODE LZO,
    "shipping"            DOUBLE PRECISION ENCODE RAW,
    "shopping_cart"       VARCHAR(5000)    ENCODE LZO,
    "tax"                 DOUBLE PRECISION ENCODE RAW,
    "total_amount"        DOUBLE PRECISION ENCODE RAW,
    "transaction_id"      VARCHAR(4096)    ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_mparticle_snowplow_product_event_1 IS 'iglu:com.mparticle.snowplow/product_event/jsonschema/1-0-0';
