-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.2.0
-- Generated: 2017-09-19 16:16

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_mparticle_snowplow_pushmessage_event_1 (
    "schema_vendor"              VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"                VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"              VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version"             VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"                    CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"                TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"                   VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"                   VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"                 VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "name"                       VARCHAR(4096) ENCODE LZO       NOT NULL,
    "action_category_identifier" VARCHAR(4096) ENCODE LZO,
    "action_identifier"          VARCHAR(4096) ENCODE LZO,
    "action_name"                VARCHAR(4096) ENCODE LZO,
    "application_state_type"     VARCHAR(4096) ENCODE LZO,
    "attributes"                 VARCHAR(4096) ENCODE LZO,
    "content_id"                 BIGINT        ENCODE LZO,
    "json_payload"               VARCHAR(4096) ENCODE LZO,
    "message"                    VARCHAR(4096) ENCODE LZO,
    "network"                    VARCHAR(4096) ENCODE LZO,
    "push_message_type"          VARCHAR(4096) ENCODE LZO,
    "token"                      VARCHAR(4096) ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_mparticle_snowplow_pushmessage_event_1 IS 'iglu:com.mparticle.snowplow/pushmessage_event/jsonschema/1-0-0';
