-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.1.0
-- Generated: 2016-09-02 17:18

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_pagerduty_incident_1 (
    "schema_vendor"                                  VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_name"                                    VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_format"                                  VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "schema_version"                                 VARCHAR(128)  ENCODE RUNLENGTH NOT NULL,
    "root_id"                                        CHAR(36)      ENCODE RAW       NOT NULL,
    "root_tstamp"                                    TIMESTAMP     ENCODE LZO       NOT NULL,
    "ref_root"                                       VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "ref_tree"                                       VARCHAR(1500) ENCODE RUNLENGTH NOT NULL,
    "ref_parent"                                     VARCHAR(255)  ENCODE RUNLENGTH NOT NULL,
    "created_on"                                     TIMESTAMP     ENCODE LZO,
    "data.incident.assigned_to"                      VARCHAR(5000) ENCODE LZO,
    "data.incident.assigned_to_user.email"           VARCHAR(4096) ENCODE LZO,
    "data.incident.assigned_to_user.html_url"        VARCHAR(4096) ENCODE LZO,
    "data.incident.assigned_to_user.id"              VARCHAR(4096) ENCODE LZO,
    "data.incident.assigned_to_user.name"            VARCHAR(4096) ENCODE LZO,
    "data.incident.created_on"                       TIMESTAMP     ENCODE LZO,
    "data.incident.escalation_policy.deleted_at"     VARCHAR(4096) ENCODE LZO,
    "data.incident.escalation_policy.id"             VARCHAR(4096) ENCODE LZO,
    "data.incident.escalation_policy.name"           VARCHAR(4096) ENCODE LZO,
    "data.incident.html_url"                         VARCHAR(4096) ENCODE LZO,
    "data.incident.id"                               VARCHAR(4096) ENCODE LZO,
    "data.incident.incident_key"                     VARCHAR(4096) ENCODE LZO,
    "data.incident.incident_number"                  BIGINT        ENCODE LZO,
    "data.incident.last_status_change_by.email"      VARCHAR(4096) ENCODE LZO,
    "data.incident.last_status_change_by.html_url"   VARCHAR(4096) ENCODE LZO,
    "data.incident.last_status_change_by.id"         VARCHAR(4096) ENCODE LZO,
    "data.incident.last_status_change_by.name"       VARCHAR(4096) ENCODE LZO,
    "data.incident.last_status_change_on"            TIMESTAMP     ENCODE LZO,
    "data.incident.number_of_escalations"            BIGINT        ENCODE LZO,
    "data.incident.pending_actions"                  VARCHAR(5000) ENCODE LZO,
    "data.incident.resolved_by_user.email"           VARCHAR(4096) ENCODE LZO,
    "data.incident.resolved_by_user.html_url"        VARCHAR(4096) ENCODE LZO,
    "data.incident.resolved_by_user.id"              VARCHAR(4096) ENCODE LZO,
    "data.incident.resolved_by_user.name"            VARCHAR(4096) ENCODE LZO,
    "data.incident.service.deleted_at"               VARCHAR(4096) ENCODE LZO,
    "data.incident.service.html_url"                 VARCHAR(4096) ENCODE LZO,
    "data.incident.service.id"                       VARCHAR(4096) ENCODE LZO,
    "data.incident.service.name"                     VARCHAR(4096) ENCODE LZO,
    "data.incident.status"                           VARCHAR(4096) ENCODE LZO,
    "data.incident.trigger_details_html_url"         VARCHAR(4096) ENCODE LZO,
    "data.incident.trigger_summary_data.client"      VARCHAR(4096) ENCODE LZO,
    "data.incident.trigger_summary_data.description" VARCHAR(4096) ENCODE LZO,
    "data.incident.trigger_summary_data.subject"     VARCHAR(4096) ENCODE LZO,
    "data.incident.trigger_type"                     VARCHAR(4096) ENCODE LZO,
    "id"                                             VARCHAR(4096) ENCODE LZO,
    "type"                                           VARCHAR(4096) ENCODE LZO,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_pagerduty_incident_1 IS 'iglu:com.pagerduty/incident/jsonschema/1-0-0';
